name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - run: |
          go build -o bin/containerd-${{ matrix.arch }} ./cmd/containerd
          go build -o bin/ctr-${{ matrix.arch }} ./cmd/ctr
        env:
          GOOS: darwin
          GOARCH: ${{ matrix.arch }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: bin/*
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
